/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarbonpulseRouteImport } from './routes/carbonpulse'
import { Route as CellsentryRouteImport } from './routes/cellsentry'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as FleetGuardianRouteImport } from './routes/fleet-guardian'
import { Route as FleetmindRouteImport } from './routes/fleetmind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonpulseRoute = CarbonpulseRouteImport.update({
  id: '/carbonpulse',
  path: '/carbonpulse',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsentryRoute = CellsentryRouteImport.update({
  id: '/cellsentry',
  path: '/cellsentry',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetGuardianRoute = FleetGuardianRouteImport.update({
  id: '/fleet-guardian',
  path: '/fleet-guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetmindRoute = FleetmindRouteImport.update({
  id: '/fleetmind',
  path: '/fleetmind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carbonpulse': typeof CarbonpulseRoute
  '/cellsentry': typeof CellsentryRoute
  '/chat': typeof ChatRoute
  '/command-center': typeof CommandCenterRoute
  '/fleet-guardian': typeof FleetGuardianRoute
  '/fleetmind': typeof FleetmindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carbonpulse': typeof CarbonpulseRoute
  '/cellsentry': typeof CellsentryRoute
  '/chat': typeof ChatRoute
  '/command-center': typeof CommandCenterRoute
  '/fleet-guardian': typeof FleetGuardianRoute
  '/fleetmind': typeof FleetmindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carbonpulse': typeof CarbonpulseRoute
  '/cellsentry': typeof CellsentryRoute
  '/chat': typeof ChatRoute
  '/command-center': typeof CommandCenterRoute
  '/fleet-guardian': typeof FleetGuardianRoute
  '/fleetmind': typeof FleetmindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carbonpulse'
    | '/cellsentry'
    | '/chat'
    | '/command-center'
    | '/fleet-guardian'
    | '/fleetmind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carbonpulse'
    | '/cellsentry'
    | '/chat'
    | '/command-center'
    | '/fleet-guardian'
    | '/fleetmind'
  id:
    | '__root__'
    | '/'
    | '/carbonpulse'
    | '/cellsentry'
    | '/chat'
    | '/command-center'
    | '/fleet-guardian'
    | '/fleetmind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarbonpulseRoute: typeof CarbonpulseRoute
  CellsentryRoute: typeof CellsentryRoute
  ChatRoute: typeof ChatRoute
  CommandCenterRoute: typeof CommandCenterRoute
  FleetGuardianRoute: typeof FleetGuardianRoute
  FleetmindRoute: typeof FleetmindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbonpulse': {
      id: '/carbonpulse'
      path: '/carbonpulse'
      fullPath: '/carbonpulse'
      preLoaderRoute: typeof CarbonpulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cellsentry': {
      id: '/cellsentry'
      path: '/cellsentry'
      fullPath: '/cellsentry'
      preLoaderRoute: typeof CellsentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-guardian': {
      id: '/fleet-guardian'
      path: '/fleet-guardian'
      fullPath: '/fleet-guardian'
      preLoaderRoute: typeof FleetGuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleetmind': {
      id: '/fleetmind'
      path: '/fleetmind'
      fullPath: '/fleetmind'
      preLoaderRoute: typeof FleetmindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarbonpulseRoute: CarbonpulseRoute,
  CellsentryRoute: CellsentryRoute,
  ChatRoute: ChatRoute,
  CommandCenterRoute: CommandCenterRoute,
  FleetGuardianRoute: FleetGuardianRoute,
  FleetmindRoute: FleetmindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
